services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
      REDIS_SERVER_NAME: redis
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
    volumes:
      - redis_data:/data
  server:
    image: todo-server
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USERNAME: username
      DB_DATABASE: db
      DB_PASSWORD: password
  client:
    image: todo-client
    build: .
    ports:
      - "4200:4200"
    environment:
      API_URL: http://localhost:3000
    depends_on:
      - server

volumes:
  redis_data:
